# Generated by Django 5.1 on 2024-08-16 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Credentials', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Structure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of Your Structure', max_length=255)),
                ('location', models.CharField(choices=[('ALP', 'Alappuzha'), ('EKM', 'Ernakulam'), ('KKD', 'Kozhikode'), ('PLK', 'Palakkad'), ('KLM', 'Kollam'), ('KNR', 'Kannur'), ('KSD', 'Kasargod'), ('IDK', 'Idukki'), ('KTM', 'Kottayam'), ('TSR', 'Thrissur'), ('PTA', 'Pathanamthitta'), ('MLP', 'Malappuram'), ('WYD', 'Wayanad'), ('TVM', 'Thiruvananthapuram')], help_text='Location of Your Structure', max_length=3)),
                ('structure_type', models.CharField(choices=[('BR', 'Bridge'), ('BL', 'Building'), ('DM', 'Dam'), ('SL', 'Slope'), ('TW', 'Tower'), ('OT', 'Other')], help_text='Type of Structure', max_length=2)),
                ('images', models.ImageField(blank=True, null=True, upload_to='structure_images/')),
            ],
        ),
    ]
